// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nested_demo.proto

package com.serial.jprotobuf.nested;

public final class NestedDemo {
  private NestedDemo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required int32 id = 2;
    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    // optional string email = 3;
    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // optional double doubleF = 4;
    /**
     * <code>optional double doubleF = 4;</code>
     */
    boolean hasDoubleF();
    /**
     * <code>optional double doubleF = 4;</code>
     */
    double getDoubleF();

    // optional float floatF = 5;
    /**
     * <code>optional float floatF = 5;</code>
     */
    boolean hasFloatF();
    /**
     * <code>optional float floatF = 5;</code>
     */
    float getFloatF();

    // optional bytes bytesF = 6;
    /**
     * <code>optional bytes bytesF = 6;</code>
     */
    boolean hasBytesF();
    /**
     * <code>optional bytes bytesF = 6;</code>
     */
    com.google.protobuf.ByteString getBytesF();

    // optional bool boolF = 7;
    /**
     * <code>optional bool boolF = 7;</code>
     */
    boolean hasBoolF();
    /**
     * <code>optional bool boolF = 7;</code>
     */
    boolean getBoolF();

    // optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];
    /**
     * <code>optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];</code>
     */
    boolean hasAttrPojo();
    /**
     * <code>optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];</code>
     */
    com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO getAttrPojo();
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              doubleF_ = input.readDouble();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              floatF_ = input.readFloat();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              bytesF_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              boolF_ = input.readBool();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO value = com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                attrPojo_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.serial.jprotobuf.nested.NestedDemo.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.serial.jprotobuf.nested.NestedDemo.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.serial.jprotobuf.nested.NestedDemo.Person.class, com.serial.jprotobuf.nested.NestedDemo.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Person.EnumAttrPOJO}
     */
    public enum EnumAttrPOJO
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STRING = 100;</code>
       */
      STRING(0, 100),
      /**
       * <code>INT = 50;</code>
       */
      INT(1, 50),
      ;

      /**
       * <code>STRING = 100;</code>
       */
      public static final int STRING_VALUE = 100;
      /**
       * <code>INT = 50;</code>
       */
      public static final int INT_VALUE = 50;


      public final int getNumber() { return value; }

      public static EnumAttrPOJO valueOf(int value) {
        switch (value) {
          case 100: return STRING;
          case 50: return INT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EnumAttrPOJO>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EnumAttrPOJO>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EnumAttrPOJO>() {
              public EnumAttrPOJO findValueByNumber(int number) {
                return EnumAttrPOJO.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.serial.jprotobuf.nested.NestedDemo.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final EnumAttrPOJO[] VALUES = values();

      public static EnumAttrPOJO valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EnumAttrPOJO(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.EnumAttrPOJO)
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double doubleF = 4;
    public static final int DOUBLEF_FIELD_NUMBER = 4;
    private double doubleF_;
    /**
     * <code>optional double doubleF = 4;</code>
     */
    public boolean hasDoubleF() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double doubleF = 4;</code>
     */
    public double getDoubleF() {
      return doubleF_;
    }

    // optional float floatF = 5;
    public static final int FLOATF_FIELD_NUMBER = 5;
    private float floatF_;
    /**
     * <code>optional float floatF = 5;</code>
     */
    public boolean hasFloatF() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float floatF = 5;</code>
     */
    public float getFloatF() {
      return floatF_;
    }

    // optional bytes bytesF = 6;
    public static final int BYTESF_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString bytesF_;
    /**
     * <code>optional bytes bytesF = 6;</code>
     */
    public boolean hasBytesF() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes bytesF = 6;</code>
     */
    public com.google.protobuf.ByteString getBytesF() {
      return bytesF_;
    }

    // optional bool boolF = 7;
    public static final int BOOLF_FIELD_NUMBER = 7;
    private boolean boolF_;
    /**
     * <code>optional bool boolF = 7;</code>
     */
    public boolean hasBoolF() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool boolF = 7;</code>
     */
    public boolean getBoolF() {
      return boolF_;
    }

    // optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];
    public static final int ATTRPOJO_FIELD_NUMBER = 8;
    private com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO attrPojo_;
    /**
     * <code>optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];</code>
     */
    public boolean hasAttrPojo() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];</code>
     */
    public com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO getAttrPojo() {
      return attrPojo_;
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      email_ = "";
      doubleF_ = 0D;
      floatF_ = 0F;
      bytesF_ = com.google.protobuf.ByteString.EMPTY;
      boolF_ = false;
      attrPojo_ = com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO.STRING;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, doubleF_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, floatF_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, bytesF_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, boolF_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, attrPojo_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, doubleF_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, floatF_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, bytesF_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, boolF_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, attrPojo_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.serial.jprotobuf.nested.NestedDemo.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.serial.jprotobuf.nested.NestedDemo.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.serial.jprotobuf.nested.NestedDemo.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.serial.jprotobuf.nested.NestedDemo.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.serial.jprotobuf.nested.NestedDemo.Person.class, com.serial.jprotobuf.nested.NestedDemo.Person.Builder.class);
      }

      // Construct using com.serial.jprotobuf.nested.NestedDemo.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        doubleF_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        floatF_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        bytesF_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        boolF_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        attrPojo_ = com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO.STRING;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.serial.jprotobuf.nested.NestedDemo.internal_static_Person_descriptor;
      }

      public com.serial.jprotobuf.nested.NestedDemo.Person getDefaultInstanceForType() {
        return com.serial.jprotobuf.nested.NestedDemo.Person.getDefaultInstance();
      }

      public com.serial.jprotobuf.nested.NestedDemo.Person build() {
        com.serial.jprotobuf.nested.NestedDemo.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.serial.jprotobuf.nested.NestedDemo.Person buildPartial() {
        com.serial.jprotobuf.nested.NestedDemo.Person result = new com.serial.jprotobuf.nested.NestedDemo.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.doubleF_ = doubleF_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.floatF_ = floatF_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bytesF_ = bytesF_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.boolF_ = boolF_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.attrPojo_ = attrPojo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.serial.jprotobuf.nested.NestedDemo.Person) {
          return mergeFrom((com.serial.jprotobuf.nested.NestedDemo.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.serial.jprotobuf.nested.NestedDemo.Person other) {
        if (other == com.serial.jprotobuf.nested.NestedDemo.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasDoubleF()) {
          setDoubleF(other.getDoubleF());
        }
        if (other.hasFloatF()) {
          setFloatF(other.getFloatF());
        }
        if (other.hasBytesF()) {
          setBytesF(other.getBytesF());
        }
        if (other.hasBoolF()) {
          setBoolF(other.getBoolF());
        }
        if (other.hasAttrPojo()) {
          setAttrPojo(other.getAttrPojo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.serial.jprotobuf.nested.NestedDemo.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.serial.jprotobuf.nested.NestedDemo.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required int32 id = 2;
      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // optional double doubleF = 4;
      private double doubleF_ ;
      /**
       * <code>optional double doubleF = 4;</code>
       */
      public boolean hasDoubleF() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double doubleF = 4;</code>
       */
      public double getDoubleF() {
        return doubleF_;
      }
      /**
       * <code>optional double doubleF = 4;</code>
       */
      public Builder setDoubleF(double value) {
        bitField0_ |= 0x00000008;
        doubleF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double doubleF = 4;</code>
       */
      public Builder clearDoubleF() {
        bitField0_ = (bitField0_ & ~0x00000008);
        doubleF_ = 0D;
        onChanged();
        return this;
      }

      // optional float floatF = 5;
      private float floatF_ ;
      /**
       * <code>optional float floatF = 5;</code>
       */
      public boolean hasFloatF() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float floatF = 5;</code>
       */
      public float getFloatF() {
        return floatF_;
      }
      /**
       * <code>optional float floatF = 5;</code>
       */
      public Builder setFloatF(float value) {
        bitField0_ |= 0x00000010;
        floatF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float floatF = 5;</code>
       */
      public Builder clearFloatF() {
        bitField0_ = (bitField0_ & ~0x00000010);
        floatF_ = 0F;
        onChanged();
        return this;
      }

      // optional bytes bytesF = 6;
      private com.google.protobuf.ByteString bytesF_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes bytesF = 6;</code>
       */
      public boolean hasBytesF() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes bytesF = 6;</code>
       */
      public com.google.protobuf.ByteString getBytesF() {
        return bytesF_;
      }
      /**
       * <code>optional bytes bytesF = 6;</code>
       */
      public Builder setBytesF(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        bytesF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes bytesF = 6;</code>
       */
      public Builder clearBytesF() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bytesF_ = getDefaultInstance().getBytesF();
        onChanged();
        return this;
      }

      // optional bool boolF = 7;
      private boolean boolF_ ;
      /**
       * <code>optional bool boolF = 7;</code>
       */
      public boolean hasBoolF() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool boolF = 7;</code>
       */
      public boolean getBoolF() {
        return boolF_;
      }
      /**
       * <code>optional bool boolF = 7;</code>
       */
      public Builder setBoolF(boolean value) {
        bitField0_ |= 0x00000040;
        boolF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolF = 7;</code>
       */
      public Builder clearBoolF() {
        bitField0_ = (bitField0_ & ~0x00000040);
        boolF_ = false;
        onChanged();
        return this;
      }

      // optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];
      private com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO attrPojo_ = com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO.STRING;
      /**
       * <code>optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];</code>
       */
      public boolean hasAttrPojo() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];</code>
       */
      public com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO getAttrPojo() {
        return attrPojo_;
      }
      /**
       * <code>optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];</code>
       */
      public Builder setAttrPojo(com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        attrPojo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Person.EnumAttrPOJO attrPojo = 8 [default = STRING];</code>
       */
      public Builder clearAttrPojo() {
        bitField0_ = (bitField0_ & ~0x00000080);
        attrPojo_ = com.serial.jprotobuf.nested.NestedDemo.Person.EnumAttrPOJO.STRING;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Person)
  }

  public interface AddressBookProtosPOJOOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .Person person = 1;
    /**
     * <code>optional .Person person = 1;</code>
     */
    boolean hasPerson();
    /**
     * <code>optional .Person person = 1;</code>
     */
    com.serial.jprotobuf.nested.NestedDemo.Person getPerson();
    /**
     * <code>optional .Person person = 1;</code>
     */
    com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder getPersonOrBuilder();

    // repeated .Person persons = 2;
    /**
     * <code>repeated .Person persons = 2;</code>
     */
    java.util.List<com.serial.jprotobuf.nested.NestedDemo.Person> 
        getPersonsList();
    /**
     * <code>repeated .Person persons = 2;</code>
     */
    com.serial.jprotobuf.nested.NestedDemo.Person getPersons(int index);
    /**
     * <code>repeated .Person persons = 2;</code>
     */
    int getPersonsCount();
    /**
     * <code>repeated .Person persons = 2;</code>
     */
    java.util.List<? extends com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder> 
        getPersonsOrBuilderList();
    /**
     * <code>repeated .Person persons = 2;</code>
     */
    com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder getPersonsOrBuilder(
        int index);

    // repeated string stringList = 3;
    /**
     * <code>repeated string stringList = 3;</code>
     */
    java.util.List<java.lang.String>
    getStringListList();
    /**
     * <code>repeated string stringList = 3;</code>
     */
    int getStringListCount();
    /**
     * <code>repeated string stringList = 3;</code>
     */
    java.lang.String getStringList(int index);
    /**
     * <code>repeated string stringList = 3;</code>
     */
    com.google.protobuf.ByteString
        getStringListBytes(int index);

    // repeated int32 intList = 4;
    /**
     * <code>repeated int32 intList = 4;</code>
     */
    java.util.List<java.lang.Integer> getIntListList();
    /**
     * <code>repeated int32 intList = 4;</code>
     */
    int getIntListCount();
    /**
     * <code>repeated int32 intList = 4;</code>
     */
    int getIntList(int index);
  }
  /**
   * Protobuf type {@code AddressBookProtosPOJO}
   */
  public static final class AddressBookProtosPOJO extends
      com.google.protobuf.GeneratedMessage
      implements AddressBookProtosPOJOOrBuilder {
    // Use AddressBookProtosPOJO.newBuilder() to construct.
    private AddressBookProtosPOJO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddressBookProtosPOJO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddressBookProtosPOJO defaultInstance;
    public static AddressBookProtosPOJO getDefaultInstance() {
      return defaultInstance;
    }

    public AddressBookProtosPOJO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddressBookProtosPOJO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.serial.jprotobuf.nested.NestedDemo.Person.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = person_.toBuilder();
              }
              person_ = input.readMessage(com.serial.jprotobuf.nested.NestedDemo.Person.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(person_);
                person_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                persons_ = new java.util.ArrayList<com.serial.jprotobuf.nested.NestedDemo.Person>();
                mutable_bitField0_ |= 0x00000002;
              }
              persons_.add(input.readMessage(com.serial.jprotobuf.nested.NestedDemo.Person.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                stringList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              stringList_.add(input.readBytes());
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                intList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              intList_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                intList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                intList_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          persons_ = java.util.Collections.unmodifiableList(persons_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          stringList_ = new com.google.protobuf.UnmodifiableLazyStringList(stringList_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          intList_ = java.util.Collections.unmodifiableList(intList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.serial.jprotobuf.nested.NestedDemo.internal_static_AddressBookProtosPOJO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.serial.jprotobuf.nested.NestedDemo.internal_static_AddressBookProtosPOJO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO.class, com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO.Builder.class);
    }

    public static com.google.protobuf.Parser<AddressBookProtosPOJO> PARSER =
        new com.google.protobuf.AbstractParser<AddressBookProtosPOJO>() {
      public AddressBookProtosPOJO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressBookProtosPOJO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBookProtosPOJO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .Person person = 1;
    public static final int PERSON_FIELD_NUMBER = 1;
    private com.serial.jprotobuf.nested.NestedDemo.Person person_;
    /**
     * <code>optional .Person person = 1;</code>
     */
    public boolean hasPerson() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Person person = 1;</code>
     */
    public com.serial.jprotobuf.nested.NestedDemo.Person getPerson() {
      return person_;
    }
    /**
     * <code>optional .Person person = 1;</code>
     */
    public com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder getPersonOrBuilder() {
      return person_;
    }

    // repeated .Person persons = 2;
    public static final int PERSONS_FIELD_NUMBER = 2;
    private java.util.List<com.serial.jprotobuf.nested.NestedDemo.Person> persons_;
    /**
     * <code>repeated .Person persons = 2;</code>
     */
    public java.util.List<com.serial.jprotobuf.nested.NestedDemo.Person> getPersonsList() {
      return persons_;
    }
    /**
     * <code>repeated .Person persons = 2;</code>
     */
    public java.util.List<? extends com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder> 
        getPersonsOrBuilderList() {
      return persons_;
    }
    /**
     * <code>repeated .Person persons = 2;</code>
     */
    public int getPersonsCount() {
      return persons_.size();
    }
    /**
     * <code>repeated .Person persons = 2;</code>
     */
    public com.serial.jprotobuf.nested.NestedDemo.Person getPersons(int index) {
      return persons_.get(index);
    }
    /**
     * <code>repeated .Person persons = 2;</code>
     */
    public com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder getPersonsOrBuilder(
        int index) {
      return persons_.get(index);
    }

    // repeated string stringList = 3;
    public static final int STRINGLIST_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList stringList_;
    /**
     * <code>repeated string stringList = 3;</code>
     */
    public java.util.List<java.lang.String>
        getStringListList() {
      return stringList_;
    }
    /**
     * <code>repeated string stringList = 3;</code>
     */
    public int getStringListCount() {
      return stringList_.size();
    }
    /**
     * <code>repeated string stringList = 3;</code>
     */
    public java.lang.String getStringList(int index) {
      return stringList_.get(index);
    }
    /**
     * <code>repeated string stringList = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStringListBytes(int index) {
      return stringList_.getByteString(index);
    }

    // repeated int32 intList = 4;
    public static final int INTLIST_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> intList_;
    /**
     * <code>repeated int32 intList = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getIntListList() {
      return intList_;
    }
    /**
     * <code>repeated int32 intList = 4;</code>
     */
    public int getIntListCount() {
      return intList_.size();
    }
    /**
     * <code>repeated int32 intList = 4;</code>
     */
    public int getIntList(int index) {
      return intList_.get(index);
    }

    private void initFields() {
      person_ = com.serial.jprotobuf.nested.NestedDemo.Person.getDefaultInstance();
      persons_ = java.util.Collections.emptyList();
      stringList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      intList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasPerson()) {
        if (!getPerson().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getPersonsCount(); i++) {
        if (!getPersons(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, person_);
      }
      for (int i = 0; i < persons_.size(); i++) {
        output.writeMessage(2, persons_.get(i));
      }
      for (int i = 0; i < stringList_.size(); i++) {
        output.writeBytes(3, stringList_.getByteString(i));
      }
      for (int i = 0; i < intList_.size(); i++) {
        output.writeInt32(4, intList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_);
      }
      for (int i = 0; i < persons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, persons_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stringList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(stringList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStringListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < intList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(intList_.get(i));
        }
        size += dataSize;
        size += 1 * getIntListList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddressBookProtosPOJO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.serial.jprotobuf.nested.NestedDemo.internal_static_AddressBookProtosPOJO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.serial.jprotobuf.nested.NestedDemo.internal_static_AddressBookProtosPOJO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO.class, com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO.Builder.class);
      }

      // Construct using com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
          getPersonsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = com.serial.jprotobuf.nested.NestedDemo.Person.getDefaultInstance();
        } else {
          personBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (personsBuilder_ == null) {
          persons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          personsBuilder_.clear();
        }
        stringList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        intList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.serial.jprotobuf.nested.NestedDemo.internal_static_AddressBookProtosPOJO_descriptor;
      }

      public com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO getDefaultInstanceForType() {
        return com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO.getDefaultInstance();
      }

      public com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO build() {
        com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO buildPartial() {
        com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO result = new com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (personBuilder_ == null) {
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        if (personsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            persons_ = java.util.Collections.unmodifiableList(persons_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.persons_ = persons_;
        } else {
          result.persons_ = personsBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          stringList_ = new com.google.protobuf.UnmodifiableLazyStringList(
              stringList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.stringList_ = stringList_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          intList_ = java.util.Collections.unmodifiableList(intList_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.intList_ = intList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO) {
          return mergeFrom((com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO other) {
        if (other == com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO.getDefaultInstance()) return this;
        if (other.hasPerson()) {
          mergePerson(other.getPerson());
        }
        if (personsBuilder_ == null) {
          if (!other.persons_.isEmpty()) {
            if (persons_.isEmpty()) {
              persons_ = other.persons_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePersonsIsMutable();
              persons_.addAll(other.persons_);
            }
            onChanged();
          }
        } else {
          if (!other.persons_.isEmpty()) {
            if (personsBuilder_.isEmpty()) {
              personsBuilder_.dispose();
              personsBuilder_ = null;
              persons_ = other.persons_;
              bitField0_ = (bitField0_ & ~0x00000002);
              personsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonsFieldBuilder() : null;
            } else {
              personsBuilder_.addAllMessages(other.persons_);
            }
          }
        }
        if (!other.stringList_.isEmpty()) {
          if (stringList_.isEmpty()) {
            stringList_ = other.stringList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStringListIsMutable();
            stringList_.addAll(other.stringList_);
          }
          onChanged();
        }
        if (!other.intList_.isEmpty()) {
          if (intList_.isEmpty()) {
            intList_ = other.intList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureIntListIsMutable();
            intList_.addAll(other.intList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasPerson()) {
          if (!getPerson().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getPersonsCount(); i++) {
          if (!getPersons(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.serial.jprotobuf.nested.NestedDemo.AddressBookProtosPOJO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .Person person = 1;
      private com.serial.jprotobuf.nested.NestedDemo.Person person_ = com.serial.jprotobuf.nested.NestedDemo.Person.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.serial.jprotobuf.nested.NestedDemo.Person, com.serial.jprotobuf.nested.NestedDemo.Person.Builder, com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder> personBuilder_;
      /**
       * <code>optional .Person person = 1;</code>
       */
      public boolean hasPerson() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Person person = 1;</code>
       */
      public com.serial.jprotobuf.nested.NestedDemo.Person getPerson() {
        if (personBuilder_ == null) {
          return person_;
        } else {
          return personBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Person person = 1;</code>
       */
      public Builder setPerson(com.serial.jprotobuf.nested.NestedDemo.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          person_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Person person = 1;</code>
       */
      public Builder setPerson(
          com.serial.jprotobuf.nested.NestedDemo.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          person_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Person person = 1;</code>
       */
      public Builder mergePerson(com.serial.jprotobuf.nested.NestedDemo.Person value) {
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              person_ != com.serial.jprotobuf.nested.NestedDemo.Person.getDefaultInstance()) {
            person_ =
              com.serial.jprotobuf.nested.NestedDemo.Person.newBuilder(person_).mergeFrom(value).buildPartial();
          } else {
            person_ = value;
          }
          onChanged();
        } else {
          personBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = com.serial.jprotobuf.nested.NestedDemo.Person.getDefaultInstance();
          onChanged();
        } else {
          personBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Person person = 1;</code>
       */
      public com.serial.jprotobuf.nested.NestedDemo.Person.Builder getPersonBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Person person = 1;</code>
       */
      public com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder getPersonOrBuilder() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          return person_;
        }
      }
      /**
       * <code>optional .Person person = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.serial.jprotobuf.nested.NestedDemo.Person, com.serial.jprotobuf.nested.NestedDemo.Person.Builder, com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.serial.jprotobuf.nested.NestedDemo.Person, com.serial.jprotobuf.nested.NestedDemo.Person.Builder, com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder>(
                  person_,
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // repeated .Person persons = 2;
      private java.util.List<com.serial.jprotobuf.nested.NestedDemo.Person> persons_ =
        java.util.Collections.emptyList();
      private void ensurePersonsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          persons_ = new java.util.ArrayList<com.serial.jprotobuf.nested.NestedDemo.Person>(persons_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.serial.jprotobuf.nested.NestedDemo.Person, com.serial.jprotobuf.nested.NestedDemo.Person.Builder, com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder> personsBuilder_;

      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public java.util.List<com.serial.jprotobuf.nested.NestedDemo.Person> getPersonsList() {
        if (personsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(persons_);
        } else {
          return personsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public int getPersonsCount() {
        if (personsBuilder_ == null) {
          return persons_.size();
        } else {
          return personsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public com.serial.jprotobuf.nested.NestedDemo.Person getPersons(int index) {
        if (personsBuilder_ == null) {
          return persons_.get(index);
        } else {
          return personsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public Builder setPersons(
          int index, com.serial.jprotobuf.nested.NestedDemo.Person value) {
        if (personsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonsIsMutable();
          persons_.set(index, value);
          onChanged();
        } else {
          personsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public Builder setPersons(
          int index, com.serial.jprotobuf.nested.NestedDemo.Person.Builder builderForValue) {
        if (personsBuilder_ == null) {
          ensurePersonsIsMutable();
          persons_.set(index, builderForValue.build());
          onChanged();
        } else {
          personsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public Builder addPersons(com.serial.jprotobuf.nested.NestedDemo.Person value) {
        if (personsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonsIsMutable();
          persons_.add(value);
          onChanged();
        } else {
          personsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public Builder addPersons(
          int index, com.serial.jprotobuf.nested.NestedDemo.Person value) {
        if (personsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonsIsMutable();
          persons_.add(index, value);
          onChanged();
        } else {
          personsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public Builder addPersons(
          com.serial.jprotobuf.nested.NestedDemo.Person.Builder builderForValue) {
        if (personsBuilder_ == null) {
          ensurePersonsIsMutable();
          persons_.add(builderForValue.build());
          onChanged();
        } else {
          personsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public Builder addPersons(
          int index, com.serial.jprotobuf.nested.NestedDemo.Person.Builder builderForValue) {
        if (personsBuilder_ == null) {
          ensurePersonsIsMutable();
          persons_.add(index, builderForValue.build());
          onChanged();
        } else {
          personsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public Builder addAllPersons(
          java.lang.Iterable<? extends com.serial.jprotobuf.nested.NestedDemo.Person> values) {
        if (personsBuilder_ == null) {
          ensurePersonsIsMutable();
          super.addAll(values, persons_);
          onChanged();
        } else {
          personsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public Builder clearPersons() {
        if (personsBuilder_ == null) {
          persons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          personsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public Builder removePersons(int index) {
        if (personsBuilder_ == null) {
          ensurePersonsIsMutable();
          persons_.remove(index);
          onChanged();
        } else {
          personsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public com.serial.jprotobuf.nested.NestedDemo.Person.Builder getPersonsBuilder(
          int index) {
        return getPersonsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder getPersonsOrBuilder(
          int index) {
        if (personsBuilder_ == null) {
          return persons_.get(index);  } else {
          return personsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public java.util.List<? extends com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder> 
           getPersonsOrBuilderList() {
        if (personsBuilder_ != null) {
          return personsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(persons_);
        }
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public com.serial.jprotobuf.nested.NestedDemo.Person.Builder addPersonsBuilder() {
        return getPersonsFieldBuilder().addBuilder(
            com.serial.jprotobuf.nested.NestedDemo.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public com.serial.jprotobuf.nested.NestedDemo.Person.Builder addPersonsBuilder(
          int index) {
        return getPersonsFieldBuilder().addBuilder(
            index, com.serial.jprotobuf.nested.NestedDemo.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .Person persons = 2;</code>
       */
      public java.util.List<com.serial.jprotobuf.nested.NestedDemo.Person.Builder> 
           getPersonsBuilderList() {
        return getPersonsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.serial.jprotobuf.nested.NestedDemo.Person, com.serial.jprotobuf.nested.NestedDemo.Person.Builder, com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder> 
          getPersonsFieldBuilder() {
        if (personsBuilder_ == null) {
          personsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.serial.jprotobuf.nested.NestedDemo.Person, com.serial.jprotobuf.nested.NestedDemo.Person.Builder, com.serial.jprotobuf.nested.NestedDemo.PersonOrBuilder>(
                  persons_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          persons_ = null;
        }
        return personsBuilder_;
      }

      // repeated string stringList = 3;
      private com.google.protobuf.LazyStringList stringList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStringListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          stringList_ = new com.google.protobuf.LazyStringArrayList(stringList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string stringList = 3;</code>
       */
      public java.util.List<java.lang.String>
          getStringListList() {
        return java.util.Collections.unmodifiableList(stringList_);
      }
      /**
       * <code>repeated string stringList = 3;</code>
       */
      public int getStringListCount() {
        return stringList_.size();
      }
      /**
       * <code>repeated string stringList = 3;</code>
       */
      public java.lang.String getStringList(int index) {
        return stringList_.get(index);
      }
      /**
       * <code>repeated string stringList = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStringListBytes(int index) {
        return stringList_.getByteString(index);
      }
      /**
       * <code>repeated string stringList = 3;</code>
       */
      public Builder setStringList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListIsMutable();
        stringList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringList = 3;</code>
       */
      public Builder addStringList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListIsMutable();
        stringList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringList = 3;</code>
       */
      public Builder addAllStringList(
          java.lang.Iterable<java.lang.String> values) {
        ensureStringListIsMutable();
        super.addAll(values, stringList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringList = 3;</code>
       */
      public Builder clearStringList() {
        stringList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringList = 3;</code>
       */
      public Builder addStringListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListIsMutable();
        stringList_.add(value);
        onChanged();
        return this;
      }

      // repeated int32 intList = 4;
      private java.util.List<java.lang.Integer> intList_ = java.util.Collections.emptyList();
      private void ensureIntListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          intList_ = new java.util.ArrayList<java.lang.Integer>(intList_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 intList = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getIntListList() {
        return java.util.Collections.unmodifiableList(intList_);
      }
      /**
       * <code>repeated int32 intList = 4;</code>
       */
      public int getIntListCount() {
        return intList_.size();
      }
      /**
       * <code>repeated int32 intList = 4;</code>
       */
      public int getIntList(int index) {
        return intList_.get(index);
      }
      /**
       * <code>repeated int32 intList = 4;</code>
       */
      public Builder setIntList(
          int index, int value) {
        ensureIntListIsMutable();
        intList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 intList = 4;</code>
       */
      public Builder addIntList(int value) {
        ensureIntListIsMutable();
        intList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 intList = 4;</code>
       */
      public Builder addAllIntList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIntListIsMutable();
        super.addAll(values, intList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 intList = 4;</code>
       */
      public Builder clearIntList() {
        intList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AddressBookProtosPOJO)
    }

    static {
      defaultInstance = new AddressBookProtosPOJO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AddressBookProtosPOJO)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressBookProtosPOJO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddressBookProtosPOJO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021nested_demo.proto\"\306\001\n\006Person\022\014\n\004name\030\001" +
      " \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005email\030\003 \001(\t\022\017\n\007doubl" +
      "eF\030\004 \001(\001\022\016\n\006floatF\030\005 \001(\002\022\016\n\006bytesF\030\006 \001(\014" +
      "\022\r\n\005boolF\030\007 \001(\010\022.\n\010attrPojo\030\010 \001(\0162\024.Pers" +
      "on.EnumAttrPOJO:\006STRING\"#\n\014EnumAttrPOJO\022" +
      "\n\n\006STRING\020d\022\007\n\003INT\0202\"o\n\025AddressBookProto" +
      "sPOJO\022\027\n\006person\030\001 \001(\0132\007.Person\022\030\n\007person" +
      "s\030\002 \003(\0132\007.Person\022\022\n\nstringList\030\003 \003(\t\022\017\n\007" +
      "intList\030\004 \003(\005B\035\n\033com.serial.jprotobuf.ne" +
      "sted"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_descriptor,
              new java.lang.String[] { "Name", "Id", "Email", "DoubleF", "FloatF", "BytesF", "BoolF", "AttrPojo", });
          internal_static_AddressBookProtosPOJO_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_AddressBookProtosPOJO_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AddressBookProtosPOJO_descriptor,
              new java.lang.String[] { "Person", "Persons", "StringList", "IntList", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
